### ISSUE TITLE
About "collision-example"

### ISSUE THREAD

**Issue by ghost** [defold/defold-examples#3]
I think examples/collision-example/spawner.script needs this...

`msg.post("main:/controls#gui", "hide_controls")`

Run camera-example then collision-example, collision-example still has camera-example's UI(Virtual Pad thingy).

![collisionnnnnn](https://cloud.githubusercontent.com/assets/5123004/26450000/32164184-4190-11e7-8812-fee8d97e78c5.png)

**Comment by britzl** [comment]
Thanks. The camera example has been updated to hide the controls when it is unloaded
