### ISSUE TITLE
Failed to load image

### ISSUE THREAD

**Issue by picasso250** [defold/defold-examples#5]
Version: 1.2.162
Channel: stable
Editor SHA1: e07f3bb9e8c970eceda8dce8efd5905fd67fa720
Engine SHA1: e07f3bb9e8c970eceda8dce8efd5905fd67fa720

```
ERROR:DLIB: Failed to load image: 'Image not of any known type, or corrupt'
WARNING:SCRIPT: failed to load image (-2)
ERROR:SCRIPT: /gui-example/gui.gui_script:41: attempt to index local 'img' (a nil value)
stack traceback:
	/gui-example/gui.gui_script:41: in function </gui-example/gui.gui_script:39>
ERROR:GAMESYS: Error when dispatching message to gui scene: -2. Message '<unknown>' sent from (null):# to default:/gui#gui.
```
it is because `http://www.defold.com/static/base/press-kit/Defold-logotypes_RGB-Original_Illustrator-01.png` is 404

**Comment by britzl** [comment]
Thanks. Yes, the site has updated and image urls have changed. Updated with a URL to the forum logo which should be more permanent.
