### ISSUE TITLE
Out of tiles to render (2048)

### ISSUE THREAD

**Issue by max91** [defold/defold-examples#7]
Hello. I start your project on macbook and have next error
ERROR:GAMESYS: Out of tiles to render (2048). You can change this with the config setting tilemap.max_tile_count

Can you help me with this problem?
Example name "War Battles"

**Comment by JCash** [comment]
That error lets you know that your tilemap uses "too many" tiles.
You can _increase_ that number by changing the number in the project settings: `tilemap.max_tile_count`

**Comment by max91** [comment]
thanks =)
