### ISSUE TITLE
Is it me or the examples here are written in GO?

### ISSUE THREAD

**Issue by UltraBurstXD** [defold/defold-examples#8]
Hi,
I'm starting to learn defold, I'm reading some topics about it and want to try some samples to get to know it more. But it looks like the examples here were written in Go... Is it GitHub error, or perhaps I'm missing something...? Shouldn't they be written in Lua scripting language?

**Comment by britzl** [comment]
The game object files have extension .go which makes GitHub confused. Defold uses Lua.

**Comment by UltraBurstXD** [comment]
Ohhh... I see... Thanks!
