### ISSUE TITLE
Blank screen in war battles tutorial sample, Ubuntu 20.10

### ISSUE THREAD

**Issue by UltraBurstXD** [defold/defold-examples#9]
Hi, I'm having some troubles running War Battles tutorials sample. My collection Tilemap is empy leaving only defaults coordinates there:
![Screenshot from 2021-02-12 14-51-08](https://user-images.githubusercontent.com/55871338/107770226-c7f5ab00-6d41-11eb-9f3a-de930947ee73.png)

This is the screen when I ran the project (I was following the README.md file)
![Screenshot from 2021-02-12 14-53-09](https://user-images.githubusercontent.com/55871338/107770440-0db27380-6d42-11eb-9d6e-6589c3ba8dec.png)

It's kinda strange, but others steps worked out...

**Comment by britzl** [comment]
I'm not sure I follow. If the tilemap is empty then the expected result is a blank screen when running the game right?

**Comment by UltraBurstXD** [comment]
Yes, I think so.

**Comment by britzl** [comment]
So what is the actual bug? I feel I'm missing something.

**Comment by UltraBurstXD** [comment]
Ohhh... It's looks like I didn't paint with brushes in map.tilemap for long time. I did that in first time, but the painted brushes were too small to be noted. I kept committing the same error afterwards.

Anyway, sorry for for the inconvenience.

**Comment by britzl** [comment]
Happy to hear you managed to solve it!
